version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: sqlite3
        versions: ">= 2" # FIXME: Remove when rails/rails#51636 will be released
      - dependency-name: json
        versions: ">= 3.0.0" # TODO: remove when a Rails release includes rails/rails#58601
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel/*"
