AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 41.39 # TODO: Lower to 15

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 12 # TODO: Lower to 7

Rails:
  Enabled: true

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment: true
