AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 18.36

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 18
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Rails:
  Enabled: true

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

# TODO: Remove when targeting Ruby 2.3 because it is already enabled.
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/SpaceAroundOperators:
  AllowForAlignment: true
