name: JavaScript tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - uses: pnpm/action-setup@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install node dependencies
      run: pnpm install
    - name: Run tests
      run: bundle exec rake test:js
